CREATE TABLE BOTTLES(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   BRAND   TEXT    NOT NULL,
   PRICE   INT,
   VOLUME  INT,
   NBR     INT

);

INSERT INTO BOTTLES (BRAND,PRICE,VOLUME,NBR)
VALUES ('Chouffe',200,25,50);
INSERT INTO BOTTLES (BRAND,PRICE,VOLUME,NBR)
VALUES ('Grimbergen',200,33,40);
INSERT INTO BOTTLES (BRAND,PRICE,VOLUME,NBR)
VALUES ('CuveeDesTrolls',300,33,10);

CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY   AUTOINCREMENT,
    USERNAME        TEXT    NOT NULL,
    PASSWORD        TEXT    NOT NULL,
    ROLE		    TEXT    NOT NULL	
);


INSERT INTO USERS (USERNAME,PASSWORD,ROLE)
VALUES ('Pierre','$2a$08$rLzvtxwZgPevf8zRVjb2PuCvFFW7SraHjrMekOmYs2luOJlRpfXRG','admin'); /* hashedPassword for "password"
